"""create users

Revision ID: 4b44a7e371b5
Revises: 
Create Date: 2020-01-12 15:27:54.065863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b44a7e371b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    op.add_column('user', sa.Column('password_hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password_hash')
    op.create_table('test',
    sa.Column('test_name', sa.VARCHAR(length=30), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
